sgd:
  raw_data_root: data/dstc8-schema-guided-dialogue
  data_prep_out_root: processed_data/simple_tod
  chatgpt_results_path: data_exploration/chatgpt/chat_gpt_all sgd.csv
  dataset_name: sgd
  data_filters: 
    - api_call