ketod_v4:
  raw_data_root: data/ketod/sgd_x/data/v4
  data_prep_out_root: processed_data/ketod/sgd_x/v4
  chatgpt_results_path: data_exploration/chatgpt/chat_gpt_all.csv
  dataset_name: ketod_v4
  version_name: 4
  original_dataset_path: data/ketod
  data_prep_transformations: 
    - schema_api_transformation