sgdx_pl4:
  raw_data_root: data/dstc8-schema-guided-dialogue/sgd_x/data/pl4
  data_prep_out_root: processed_data/sgd_x/pl4
  chatgpt_results_path: data_exploration/chatgpt/chat_gpt_all_sgd.csv
  dataset_name: sgdx_pl4