sgdx_v2:
  raw_data_root: data/dstc8-schema-guided-dialogue/sgd_x/data/v2
  data_prep_out_root: processed_data/sgd_x/v2
  chatgpt_results_path: data_exploration/chatgpt/chat_gpt_all sgd.csv
  dataset_name: sgdx_v2
  data_filter: api_call
  data_filters: 
    - api_call