model_a: 
  path: outputs/2023-05-31/20-33-34/results/pretrain
  domains:
    - Restaurants_1
model_b: 
  path: outputs/2023-06-03/21-05-36/results/pretrain
  domains:
    - Movies_1
model_multi_domain: 
  path: outputs/2023-06-03/21-14-45/results/pretrain
  domains:
    - Restaurants_1
    - Movies_1
num_test_dialogs: 1
train_step_data:
  num_dialog: 1
  overwrite: true
  split_percent: 1
  # domain_settings: ${model_multi_domain.domains}
  domain_settings: ${model_a.domains}
postprocess_generation: true
wandb:
  project: ZSTodLocal
  entity: adibm
  notes: testing arithmetic multidomain
  task: arithmetic
test_batch_size : 8
data_split_percent : [.1 , 1 , 1]
model_name: huggyllama/llama-7b
quantization: true
create_data_from_train: true
create_data_from_train_splits:
  - 0.01
  - 0.01