channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - comm=0.2.2
  - debugpy=1.8.8
  - decorator=5.1.1
  - executing=2.1.0
  - ipykernel=6.29.5
  - ipython=8.29.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - ld_impl_linux-64=2.38
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libsodium=1.0.20
  - libstdcxx=14.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - ninja-base=1.12.1
  - openssl=3.4.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - prompt-toolkit=3.0.48
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - python=3.10.13
  - python_abi=3.10
  - pyzmq=26.2.0
  - readline=8.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.2
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - accelerate==0.30.1
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.3.0
      - appdirs==1.4.4
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - attrs==23.1.0
      - bert-score==0.3.13
      - bitsandbytes==0.43.1
      - black==23.11.0
      - build==1.0.3
      - cachecontrol==0.13.1
      - captum==0.7.0
      - certifi==2023.11.17
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - class-registry==2.1.2
      - cleo==2.1.0
      - click==8.1.7
      - cmake==3.27.9
      - contourpy==1.2.0
      - crashtest==0.4.1
      - cryptography==41.0.7
      - cycler==0.12.1
      - dataclass-csv==1.4.0
      - dataclasses-json==0.5.9
      - dataproperty==1.0.1
      - datasets==2.15.0
      - deepspeed==0.12.4
      - dill==0.3.7
      - distlib==0.3.7
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.15
      - dotmap==1.3.30
      - dulwich==0.21.6
      - evaluate==0.4.1
      - exceptiongroup==1.2.0
      - fastjsonschema==2.19.0
      - filelock==3.13.1
      - flatbuffers==24.3.25
      - fonttools==4.46.0
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - fuzzywuzzy==0.18.0
      - gast==0.6.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-pasta==0.2.0
      - grpcio==1.66.1
      - h11==0.14.0
      - h5py==3.11.0
      - hjson==3.1.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.24.5
      - hurry==1.1
      - hurry-filesize==0.9
      - hydra-core==1.3.2
      - idna==3.6
      - importlib-metadata==7.0.0
      - iniconfig==2.0.0
      - installer==0.7.0
      - jaraco-classes==3.3.0
      - jeepney==0.8.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - keras==3.5.0
      - keyring==24.3.0
      - kiwisolver==1.4.5
      - langdetect==1.0.9
      - levenshtein==0.23.0
      - libclang==18.1.1
      - lightning-utilities==0.10.0
      - lit==17.0.6
      - loralib==0.1.2
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - marshmallow==3.20.1
      - marshmallow-enum==1.5.1
      - matplotlib==3.8.2
      - mbstrdecoder==1.1.3
      - mdurl==0.1.2
      - ml-dtypes==0.4.0
      - more-itertools==10.1.0
      - mpmath==1.3.0
      - msgpack==1.0.7
      - multidict==6.0.4
      - multiprocess==0.70.15
      - mypy-extensions==1.0.0
      - namex==0.0.8
      - networkx==3.2.1
      - ninja==1.11.1.1
      - nltk==3.8.1
      - numerize==0.12
      - numpy==1.26.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - omegaconf==2.3.0
      - openai==1.28.1
      - opt-einsum==3.3.0
      - optree==0.12.1
      - packaging==23.2
      - pandas==2.1.3
      - pathos==0.3.1
      - pathspec==0.11.2
      - pathtools==0.1.2
      - pathvalidate==3.2.0
      - peft==0.11.1
      - pillow==10.1.0
      - pkginfo==1.9.6
      - platformdirs==3.11.0
      - pluggy==1.3.0
      - poetry==1.7.1
      - poetry-core==1.8.1
      - poetry-plugin-export==1.6.0
      - pox==0.3.3
      - ppft==1.7.6.7
      - protobuf==4.25.1
      - psutil==5.9.6
      - py-cpuinfo==9.0.0
      - pyarrow==14.0.1
      - pyarrow-hotfix==0.6
      - pycparser==2.21
      - pydantic==2.5.2
      - pydantic-core==2.14.5
      - pygments==2.17.2
      - pyhumps==3.8.0
      - pynvml==11.5.0
      - pyparsing==3.1.1
      - pyproject-hooks==1.0.0
      - pytablewriter==1.2.0
      - pytest==7.4.3
      - python-dateutil==2.8.2
      - python-levenshtein==0.23.0
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - rapidfuzz==3.5.2
      - regex==2023.10.3
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - responses==0.18.0
      - rich==13.7.0
      - rouge-score==0.1.2
      - safetensors==0.4.1
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - seaborn==0.12.2
      - secretstorage==3.3.3
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - sentry-sdk==1.38.0
      - setproctitle==1.3.3
      - setuptools==69.0.2
      - sgd-dstc8-data-model==0.1.9
      - shellingham==1.5.4
      - shtab==1.6.5
      - smmap==5.0.1
      - sniffio==1.3.1
      - sympy==1.12
      - tabledata==1.3.3
      - tcolorpy==0.1.6
      - tensorboard-data-server==0.7.2
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.4.0
      - tf-keras==2.17.0
      - threadpoolctl==3.2.0
      - tokenizers==0.19.1
      - tomli==2.0.1
      - tomlkit==0.12.3
      - torch==2.0.1
      - torchaudio==2.0.2
      - torchmetrics==1.2.1
      - torchvision==0.15.2
      - tqdm==4.66.1
      - transformers==4.44.2
      - triton==2.0.0
      - trl==0.7.4
      - trove-classifiers==2023.11.29
      - typepy==1.3.2
      - typing-extensions==4.8.0
      - typing-inspect==0.9.0
      - tyro==0.6.0
      - tzdata==2023.3
      - urllib3==2.1.0
      - virtualenv==20.25.0
      - wandb==0.14.2
      - werkzeug==3.0.4
      - wrapt==1.16.0
      - xxhash==3.4.1
      - yarl==1.9.3
      - zipp==3.17.0
