channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3.1
  - python=3.10.13
  - readline=8.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - accelerate==0.25.0
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - bert-score==0.3.13
      - bitsandbytes==0.41.2.post2
      - black==23.11.0
      - build==1.0.3
      - cachecontrol==0.13.1
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - class-registry==2.1.2
      - cleo==2.1.0
      - click==8.1.7
      - cmake==3.27.9
      - contourpy==1.2.0
      - crashtest==0.4.1
      - cryptography==41.0.7
      - cycler==0.12.1
      - dataclass-csv==1.4.0
      - dataclasses-json==0.5.9
      - datasets==2.15.0
      - deepspeed==0.12.4
      - dill==0.3.7
      - distlib==0.3.7
      - docker-pycreds==0.4.0
      - docstring-parser==0.15
      - dotmap==1.3.30
      - dulwich==0.21.6
      - evaluate==0.4.1
      - exceptiongroup==1.2.0
      - fastjsonschema==2.19.0
      - filelock==3.13.1
      - fonttools==4.46.0
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - fuzzywuzzy==0.18.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - hjson==3.1.0
      - huggingface-hub==0.19.4
      - hurry==1.1
      - hurry-filesize==0.9
      - hydra-core==1.3.2
      - idna==3.6
      - importlib-metadata==7.0.0
      - iniconfig==2.0.0
      - installer==0.7.0
      - jaraco-classes==3.3.0
      - jeepney==0.8.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - keyring==24.3.0
      - kiwisolver==1.4.5
      - langdetect==1.0.9
      - levenshtein==0.23.0
      - lightning-utilities==0.10.0
      - lit==17.0.6
      - loralib==0.1.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - marshmallow==3.20.1
      - marshmallow-enum==1.5.1
      - matplotlib==3.8.2
      - mdurl==0.1.2
      - more-itertools==10.1.0
      - mpmath==1.3.0
      - msgpack==1.0.7
      - multidict==6.0.4
      - multiprocess==0.70.15
      - mypy-extensions==1.0.0
      - networkx==3.2.1
      - ninja==1.11.1.1
      - nltk==3.8.1
      - numerize==0.12
      - numpy==1.26.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - omegaconf==2.3.0
      - packaging==23.2
      - pandas==2.1.3
      - pathos==0.3.1
      - pathspec==0.11.2
      - pathtools==0.1.2
      - peft==0.6.2
      - pexpect==4.9.0
      - pillow==10.1.0
      - pkginfo==1.9.6
      - platformdirs==3.11.0
      - pluggy==1.3.0
      - poetry==1.7.1
      - poetry-core==1.8.1
      - poetry-plugin-export==1.6.0
      - pox==0.3.3
      - ppft==1.7.6.7
      - protobuf==4.25.1
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - py-cpuinfo==9.0.0
      - pyarrow==14.0.1
      - pyarrow-hotfix==0.6
      - pycparser==2.21
      - pydantic==2.5.2
      - pydantic-core==2.14.5
      - pygments==2.17.2
      - pyhumps==3.8.0
      - pynvml==11.5.0
      - pyparsing==3.1.1
      - pyproject-hooks==1.0.0
      - pytest==7.4.3
      - python-dateutil==2.8.2
      - python-levenshtein==0.23.0
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - rapidfuzz==3.5.2
      - regex==2023.10.3
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - responses==0.18.0
      - rich==13.7.0
      - rouge-score==0.1.2
      - safetensors==0.4.1
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - seaborn==0.12.2
      - secretstorage==3.3.3
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - sentry-sdk==1.38.0
      - setproctitle==1.3.3
      - setuptools==69.0.2
      - sgd-dstc8-data-model==0.1.9
      - shellingham==1.5.4
      - shtab==1.6.5
      - six==1.16.0
      - smmap==5.0.1
      - sympy==1.12
      - threadpoolctl==3.2.0
      - tokenizers==0.15.0
      - tomli==2.0.1
      - tomlkit==0.12.3
      - torch==2.0.1
      - torchaudio==2.0.2
      - torchmetrics==1.2.1
      - torchvision==0.15.2
      - tqdm==4.66.1
      - transformers==4.36.1
      - triton==2.0.0
      - trl==0.7.4
      - trove-classifiers==2023.11.29
      - typing-extensions==4.8.0
      - typing-inspect==0.9.0
      - tyro==0.6.0
      - tzdata==2023.3
      - urllib3==2.1.0
      - virtualenv==20.25.0
      - wandb==0.14.2
      - xxhash==3.4.1
      - yarl==1.9.3
      - zipp==3.17.0
