channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - cffi=1.14.6
  - cryptography=37.0.2
  - cudatoolkit=11.6.0
  - ffmpeg=4.3
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - intel-openmp=2022.0.1
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - mkl=2022.0.1
  - ncurses=6.3
  - nettle=3.6
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1o
  - pip=21.2.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.7
  - python_abi=3.9
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - readline=8.1.2
  - requests=2.28.1
  - setuptools=61.2.0
  - sqlite=3.38.5
  - tk=8.6.12
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.0
  - pip:
    - absl-py==1.1.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - antlr4-python3-runtime==4.9.3
    - async-timeout==4.0.2
    - attrs==21.4.0
    - black==22.6.0
    - cachetools==5.2.0
    - charset-normalizer==2.1.0
    - click==8.1.3
    - cycler==0.11.0
    - dataclass-csv==1.4.0
    - dataclasses-json==0.5.7
    - datasets==2.3.2
    - dill==0.3.5.1
    - dotmap==1.3.30
    - evaluate==0.1.2
    - filelock==3.7.1
    - fonttools==4.34.3
    - frozenlist==1.3.0
    - fsspec==2022.5.0
    - google-auth==2.9.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - huggingface-hub==0.8.1
    - hydra-core==1.2.0
    - idna==3.3
    - importlib-metadata==4.12.0
    - iniconfig==1.1.1
    - joblib==1.1.0
    - kiwisolver==1.4.3
    - markdown==3.3.7
    - marshmallow==3.17.0
    - marshmallow-enum==1.5.1
    - matplotlib==3.5.2
    - multidict==6.0.2
    - multiprocess==0.70.13
    - mypy-extensions==0.4.3
    - nltk==3.7
    - numerize==0.12
    - numpy==1.23.0
    - oauthlib==3.2.0
    - omegaconf==2.2.2
    - packaging==21.3
    - pandas==1.4.3
    - pathos==0.2.9
    - pathspec==0.9.0
    - pillow==9.2.0
    - platformdirs==2.5.2
    - pluggy==1.0.0
    - pox==0.3.1
    - ppft==1.7.6.5
    - protobuf==3.19.4
    - py==1.11.0
    - pyarrow==8.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.2
    - pyhumps==3.7.2
    - pyparsing==3.0.9
    - pytest==7.1.2
    - python-dateutil==2.8.2
    - pytorch-lightning==1.6.4
    - pytz==2022.1
    - pyyaml==6.0
    - regex==2022.6.2
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rouge-score==0.1.2
    - rsa==4.8
    - scikit-learn==1.1.1
    - scipy==1.8.1
    - seaborn==0.11.2
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.97
    - six==1.16.0
    - sklearn==0.0
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - threadpoolctl==3.1.0
    - tokenizers==0.12.1
    - tomli==2.0.1
    - torch==1.12.1
    - torch-tb-profiler==0.4.0
    - torchaudio==0.12.1+cu113
    - torchmetrics==0.9.2
    - torchvision==0.13.1
    - tqdm==4.64.0
    - transformers==4.20.1
    - typing-extensions==4.3.0
    - typing-inspect==0.7.1
    - urllib3==1.26.9
    - werkzeug==2.1.2
    - xxhash==3.0.0
    - yarl==1.7.2
    - zipp==3.8.0
