channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - brotlipy=0.7.0
  - ca-certificates=2022.07.19
  - certifi=2022.9.24
  - cffi=1.15.1
  - conda=22.9.0
  - conda-package-handling=1.9.0
  - cryptography=38.0.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - idna=3.4
  - ipykernel=6.6.1
  - ipython=8.4.0
  - jedi=0.18.1
  - jupyter_client=7.3.5
  - jupyter_core=4.11.1
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - matplotlib-inline=0.1.6
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - openssl=1.1.1q
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycosat=0.6.3
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.8.10
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pyzmq=23.2.0
  - readline=8.2
  - requests=2.28.1
  - ruamel_yaml=0.15.100
  - six=1.16.0
  - sqlite=3.39.3
  - stack_data=0.2.0
  - tk=8.6.12
  - toolz=0.11.2
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.1.1
  - urllib3=1.26.12
  - wcwidth=0.2.5
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - antlr4-python3-runtime==4.8
    - async-timeout==4.0.2
    - attrs==21.4.0
    - black==22.3.0
    - cachetools==5.0.0
    - charset-normalizer==2.0.12
    - cloudpickle==2.0.0
    - commonmark==0.9.1
    - cycler==0.11.0
    - docstring-parser==0.13
    - fonttools==4.30.0
    - frozenlist==1.3.0
    - fsspec==2022.2.0
    - future==0.18.2
    - google-api-core==2.7.1
    - google-auth==2.6.2
    - google-auth-httplib2==0.1.0
    - google-auth-oauthlib==0.4.6
    - google-cloud-core==2.2.3
    - google-cloud-storage==2.2.1
    - google-crc32c==1.3.0
    - google-resumable-media==2.3.2
    - googleapis-common-protos==1.56.0
    - grpcio==1.44.0
    - httplib2==0.20.4
    - hydra-core==1.1.1
    - importlib-metadata==4.11.3
    - importlib-resources==5.6.0
    - jsonargparse==4.5.0
    - kiwisolver==1.3.2
    - markdown==3.3.6
    - matplotlib==3.5.1
    - multidict==6.0.2
    - numpy==1.22.0
    - oauthlib==3.2.0
    - omegaconf==2.1.1
    - packaging==21.3
    - pillow==9.0.1
    - protobuf==3.19.4
    - psutil==5.9.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.1
    - pyparsing==3.0.7
    - pytorch-lightning==1.6.0
    - pyyaml==6.0
    - requests-oauthlib==1.3.1
    - rich==12.2.0
    - rsa==4.8
    - setuptools==59.5.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - torch==1.11.0
    - torchmetrics==0.7.2
    - torchtext==0.12.0
    - typing-extensions==4.1.1
    - uritemplate==4.1.1
    - werkzeug==2.0.3
    - yarl==1.7.2
    - zipp==3.7.0
