channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - cuda=11.6.2
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=12.1.55
  - cuda-libraries=11.6.2
  - cuda-libraries-dev=11.6.2
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.1.55
  - cuda-nsight-compute=12.1.0
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=12.1.55
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.1.55
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=12.1.55
  - cuda-runtime=11.6.2
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=12.1.55
  - cuda-toolkit=11.6.2
  - cuda-tools=11.6.2
  - cuda-visual-tools=11.6.2
  - ffmpeg=4.3
  - flit-core=3.8.0
  - freetype=2.12.1
  - gds-tools=1.6.0.25
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2021.4.0
  - jinja2=3.1.2
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcufile=1.6.0.25
  - libcufile-dev=1.6.0.25
  - libcurand=10.3.2.56
  - libcurand-dev=10.3.2.56
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - ncurses=6.4
  - nettle=3.7.3
  - nsight-compute=2023.1.0.15
  - openh264=2.1.1
  - openssl=1.1.1t
  - pillow=9.4.0
  - pip=23.0.1
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.10.10
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - readline=8.2
  - six=1.16.0
  - sqlite=3.41.1
  - sympy=1.11.1
  - tk=8.6.12
  - torchtriton=2.0.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.5.4
  - pip:
    - absl-py==1.4.0
    - accelerate==0.18.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.9.3
    - appdirs==1.4.4
    - async-timeout==4.0.2
    - attrs==22.2.0
    - bitsandbytes==0.37.2
    - black==23.3.0
    - build==0.10.0
    - cachecontrol==0.12.11
    - cchardet==2.1.7
    - chardet==5.1.0
    - charset-normalizer==3.1.0
    - cleo==2.0.1
    - click==8.1.3
    - cmake==3.26.1
    - contourpy==1.0.7
    - crashtest==0.4.1
    - cryptography==40.0.1
    - cycler==0.11.0
    - dataclass-csv==1.4.0
    - dataclasses-json==0.5.7
    - datasets==2.11.0
    - dill==0.3.6
    - distlib==0.3.6
    - docker-pycreds==0.4.0
    - dotmap==1.3.30
    - dulwich==0.21.3
    - evaluate==0.4.0
    - filelock==3.10.7
    - fonttools==4.39.3
    - frozenlist==1.3.3
    - fsspec==2023.3.0
    - fuzzywuzzy==0.18.0
    - gitdb==4.0.10
    - gitpython==3.1.31
    - html5lib==1.1
    - huggingface-hub==0.13.3
    - hydra-core==1.3.2
    - importlib-metadata==6.1.0
    - installer==0.7.0
    - jaraco-classes==3.2.3
    - jeepney==0.8.0
    - joblib==1.2.0
    - jsonschema==4.17.3
    - keyring==23.13.1
    - kiwisolver==1.4.4
    - lit==16.0.0
    - lockfile==0.12.2
    - loralib==0.1.1
    - markupsafe==2.1.2
    - marshmallow==3.19.0
    - marshmallow-enum==1.5.1
    - matplotlib==3.7.1
    - more-itertools==9.1.0
    - mpmath==1.3.0
    - msgpack==1.0.5
    - multidict==6.0.4
    - multiprocess==0.70.14
    - mypy-extensions==1.0.0
    - networkx==3.0
    - nltk==3.8.1
    - numerize==0.12
    - numpy==1.24.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - omegaconf==2.3.0
    - packaging==23.0
    - pandas==1.5.3
    - pathos==0.3.0
    - pathspec==0.11.1
    - pathtools==0.1.2
    - peft==0.3.0.dev0
    - pexpect==4.8.0
    - pkginfo==1.9.6
    - platformdirs==3.2.0
    - poetry==1.4.1
    - poetry-core==1.5.2
    - poetry-plugin-export==1.3.0
    - pox==0.3.2
    - ppft==1.7.6.6
    - protobuf==4.22.1
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pyarrow==11.0.0
    - pyhumps==3.8.0
    - pyparsing==3.0.9
    - pyproject-hooks==1.0.0
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - pytz==2023.3
    - pyyaml==6.0
    - rapidfuzz==2.13.7
    - regex==2023.3.23
    - requests==2.28.2
    - requests-toolbelt==0.10.1
    - responses==0.18.0
    - rouge-score==0.1.2
    - scikit-learn==1.2.2
    - scipy==1.9.3
    - seaborn==0.12.2
    - secretstorage==3.3.3
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.97
    - sentry-sdk==1.18.0
    - setproctitle==1.3.2
    - setuptools==67.6.1
    - shellingham==1.5.0.post1
    - smmap==5.0.0
    - threadpoolctl==3.1.0
    - tokenizers==0.13.2
    - tomli==2.0.1
    - tomlkit==0.11.7
    - torch==1.13.1
    - torchaudio==0.13.1+cu116
    - torchmetrics==0.11.4
    - torchvision==0.15.1
    - tqdm==4.65.0
    - transformers==4.28.0.dev0
    - triton==2.0.0
    - trove-classifiers==2023.3.9
    - typing-extensions==4.5.0
    - typing-inspect==0.8.0
    - urllib3==1.26.15
    - virtualenv==20.21.0
    - wandb==0.14.0
    - webencodings==0.5.1
    - wheel==0.40.0
    - xxhash==3.2.0
    - yarl==1.8.2
    - zipp==3.15.0
