pretrain_epochs: 1
train_epochs: 1
pretrain_batch_size: 8
train_batch_size: 8
num_workers: 1
data_split_percent:
- 1
- 1
- 1
eval_batch_size: 40
eval_steps: 100
test_batch_size: 60
test_prompt_max_len: 750
max_token_len: 1024
num_dialogs:
- 1
- 1
- 1
# overwrite:
#   - true
#   - true
#   - true
should_test: true
train_domain_settings:
  - Restaurants_1
dev_domain_settings:
  - Restaurants_1
test_domain_settings:
  - [Restaurants_1]
# train_domain_settings:
#   - Restaurants_1
#   - RideSharing_1
# dev_domain_settings:
#   - Restaurants_1
#   - RideSharing_1
test_domain_settings:
  - [Restaurants_1, RideSharing_1]
create_data_from_train: true
create_data_from_train_splits:
  - 0.1
  - 0.1
wandb:
  project: ZSTodLocal
  entity: adibm
  notes: testing arithmetic
  task: arithmetic
model_name: distilgpt2
fp16: true
gradient_accumulation_steps: 4
