pretrain_epochs: 1
pretrain_model_path: outputs/2022-09-29/10-36-13/results/pretrain/
train_epochs: 1
train_batch_size: 6
data_split_percent:
  - .1
  - .1
  - .1
eval_batch_size: 10
test_batch_size: 30
context_max_len: 100
num_dialogs: 
  - 1
  - 1
  - 1
# overwrite:
#   - true
#   - true
#   - true
should_test: true
num_turns: 26
train_domain_setting: all
is_multi_task: true
multi_tasks:
  - 1
  - 1
  - 0
# should_add_schema: true
# should_add_sys_actions: true
# should_add_user_actions: true