model_name: gpt2
# model_path: ""
# model_path: "playground/t5_tod_out/2024-07-06/02-18-11/results"
model_path: playground/t5_tod_out/2024-07-06/03-46-30/results
train_batch_size: 40
eval_batch_size: 50
test_batch_size: 80
gradient_accumulation_steps: 32
eval_accumulation_steps: 32
quantization: false