raw_data_root: data/dstc8-schema-guided-dialogue
data_prep_out_root: processed_data/simple_tod
# context_type: nlg_api_call
context_type: gpt_api_call
# context_type: bitod
chatgpt_results_path: data_exploration/chatgpt/chat_gpt_all sgd.csv