hydra:
  run:
    dir: ./playground/t5_tod_out/${now:%Y-%m-%d}/${now:%H-%M-%S}
project_root: /home/tamim/TOD/myzstod/
raw_data_root: data/dstc8-schema-guided-dialogue/
processed_data_root: processed_data/simple_tod
dataset_name: sgd
# raw_data_root: data/bitod
# processed_data_root: processed_data/bitod
# raw_data_root: data/ketod
# processed_data_root: processed_data/ketod
max_token_len: 1024
test_prompt_max_len: 750
out_dir: results
#prompt_type: chatgpt
prompt_type: chatgptv2
# prompt_type: auto_tod
# context_type: nlg_api_call
# context_type: ketod_api_call
# context_type: bitod
overwrite: 
  - 1
  - 1
  - 1
train_domain_settings: seen
dev_domain_settings:
  - all
test_domain_settings:
  - [all]
  # - ['Buses_3','RentalCars_3','Buses_3,RentalCars_3','Services_4,Payment_1,Restaurants_2', 'Services_4', 'Restaurants_2']
  # - ['Buses_3,RentalCars_3', 'Restaurants_2']
data_split_percent: 
  - 1
  - 1
  - 1
# num_dialogs: 34
num_dialogs: 
  - 127
  - 1
  - 34
  # - 1
  # - -1
model_type:
  context_type: nlg_api_call
step_name: test
num_turns: 26
should_add_schema: true
should_add_user_actions: false
should_add_service_results: true
# response_path: data_exploration/chatgpt/chat_gpt_all.csv
# response_path: playground/t5_tod_out/2024-06-22/23-27-20/results/chatgpt_inference.csv
response_path: ""
is_multi_process: true
data_prep_multi_process: true
# data_prep_multi_process: false
is_mini_sample: false