data_split_percent:
  - 1
  - 1
  - 0.01
eval_batch_size: 6
test_batch_size: 10
max_token_len: 1000
test_prompt_max_len: 650
num_test_dialogs: 1
# num_test_dialogs: 5
project_root: /mounts/u-amo-d1/adibm-data/projects/ZSToD/
wandb:
  project: ZSTodLocal
  entity: adibm
  notes: inference adapters on full dataset
  task: arithmetic
# raw_data_root: data/dstc8-schema-guided-dialogue/sgd_x/data/
# model: outputs/2023-05-31/20-33-34/results/pretrain
# model: outputs/2023-06-05/15-00-51/results/pretrain
# model: outputs/2023-06-07/23-27-31/results/multi_task/dsts
model_paths : 
  # dsts: outputs/2023-09-24/02-09-01/results/multi_task
  actions: outputs/2023-09-25/17-17-28/results/multi_task
num_turns: 26
data_prep_multi_process: true
# overwrite:
#   - true
#   - true
#   - true
test_domain_settings:
  - [all]
  # - [seen]
  # - [unseen]
  # - [Travel_1]
  # - [RentalCars_3]
  # - - Restaurants_1
    # - Movies_1
tokenizer_name: adibm/sgd-opt-tokenizer
base_model_name: facebook/opt-2.7b
# base_model_name: huggyllama/llama-7b
model_name: facebook/opt-2.7b
# is_multi_head: true
should_add_schema: true
should_add_user_actions: true
# should_add_sys_actions: true
should_add_service_results: true
# context_type: default
postprocess_generation: false
quantization: true
quantization_dtype: 16
create_data_from_train: false
create_data_from_train_splits:
  - 0.01
  - 0.01
num_train_dialogs: 1
is_multi_task: true
multi_tasks:
  # - dsts
  - actions
  # - nlg