data_split_percent:
  - 1
  - 1
  - .01
eval_batch_size: 6
test_batch_size: 70
max_token_len: 700
num_test_dialogs: 1
model : outputs/2022-09-29/15-04-55/results/train/checkpoint-39
num_turns: 26
# overwrite:
#   - true
#   - true
#   - true
test_domain_settings:
  - all
  # - seen
  # - unseen
is_multi_task: True
multi_tasks:
  - 1
  - 1
  - 0