data_split_percent:
  - 1
  - 1
  - 1
eval_batch_size: 6
test_batch_size: 30
max_token_len: 1024
test_prompt_max_len: 750
num_test_dialogs: 17
# model: outputs/2022-10-12/18-43-31/results/train/checkpoint-10849
model: outputs/2022-10-19/22-16-52/results/train/checkpoint-9041
num_turns: 26
# overwrite:
#   - true
#   - true
#   - true
test_domain_settings:
  - all
  - seen
  - unseen
# is_multi_task: True
multi_tasks:
  - 1
  - 1
  - 0
# should_add_schema: true
should_add_user_actions: true