data_split_percent:
  - 1
  - 1
  - 1
eval_batch_size: 6
test_batch_size: 20
max_token_len: 1024
test_prompt_max_len: 500
# num_test_dialogs: 34
num_test_dialogs: 1
# raw_data_root: data/dstc8-schema-guided-dialogue/sgd_x/data/
model: outputs/2023-01-17/01-19-37/results/train
# model: outputs/2022-12-31/16-12-57/results/train
num_turns: 26
# overwrite:
#   - true
#   - true
#   - true
test_domain_settings:
  - all
  - seen
  - unseen
# is_multi_task: True
multi_tasks:
  - 1
  - 1
  - 0
is_multi_head: true
should_add_schema: true
should_add_user_actions: true
should_add_sys_actions: true
# context_type: default
should_add_service_results: true
postprocess_generation: true
# model_name: t5-base