project_root: /mounts/u-amo-d1/adibm-data/projects/ZSToD/
raw_data_root: data/bitod
processed_data_root: processed_data/bitod
num_dialogs: 1
step_name: dev
delexicalize: false
overwrite: true
num_turns: 26
is_scale_grad: false
domain_setting: all
should_add_schema: true
data_prep_multi_process: false
should_add_service_results: true
context_type: bitod
otgy_file: otgy.json
out_file: schema.json
# context_type: short_repr
