project_root: /mounts/u-amo-d0/grad/adibm/projects/generative_tod/
data_root: data/dstc8-schema-guided-dialogue/
out_root: processed_data/simple_tod
num_dialogs: 
  - 1
  - 1
  - 34
# num_dialogs: 
#   - None
#   - None
#   - None
delexicalize: false
overwrite:
  - true
  - true
  - true
num_turns: 26